builds:

  alpine-edge:
    context: /
    dockerfile: Dockerfiles/Alpine/edge/Dockerfile
    pushes:
      - "on_branch:master=didstopia/base:alpine-edge"
    labels:
      - "org.label-schema.vendor=Didstopia"
      - "org.label-schema.name=Base Docker image for Alpine."
      - "org.label-schema.version=alpine-edge"
      - "org.label-schema.description=An always up to date base image for Alpine."
      - "org.label-schema.url=https://github.com/Didstopia/docker-base-images"
      - "org.label-schema.vcs-url=github.com:Didstopia/docker-base-images.git"
      - "org.label-schema.vcs-ref={fcommitid}"
      - "org.label-schema.schema-version=1.0"

  static-alpine-edge:
    context: /
    dockerfile: Dockerfiles/Alpine/edge/static/Dockerfile
    depends_on:
      - alpine-edge
    pushes:
      - "on_branch:master=didstopia/base:static-alpine-edge"
    labels:
      - "org.label-schema.vendor=Didstopia"
      - "org.label-schema.name=Base Docker image for static hosting."
      - "org.label-schema.version=static-alpine-edge"
      - "org.label-schema.description=An always up to date base image for static hosting."
      - "org.label-schema.url=https://github.com/Didstopia/docker-base-images"
      - "org.label-schema.vcs-url=github.com:Didstopia/docker-base-images.git"
      - "org.label-schema.vcs-ref={fcommitid}"
      - "org.label-schema.schema-version=1.0"
  
  nodejs-alpine-edge:
    context: /
    dockerfile: Dockerfiles/Alpine/edge/nodejs/Dockerfile
    depends_on:
      - alpine-edge
    pushes:
      - "on_branch:master=didstopia/base:nodejs-alpine-edge"
    labels:
      - "org.label-schema.vendor=Didstopia"
      - "org.label-schema.name=Base Docker image for Node.js LTS."
      - "org.label-schema.version=nodejs-alpine-edge"
      - "org.label-schema.description=An always up to date base image for Node.js LTS."
      - "org.label-schema.url=https://github.com/Didstopia/docker-base-images"
      - "org.label-schema.vcs-url=github.com:Didstopia/docker-base-images.git"
      - "org.label-schema.vcs-ref={fcommitid}"
      - "org.label-schema.schema-version=1.0"
