builds:

  alpine-3.5:
    context: /
    dockerfile: Dockerfiles/Alpine/3.5/Dockerfile
    pushes:
      - "on_branch:master=didstopia/base:alpine-3.5"
    labels:
      - "org.label-schema.vendor=Didstopia"
      - "org.label-schema.name=Base Docker image for Alpine."
      - "org.label-schema.version=alpine-3.5"
      - "org.label-schema.description=An always up to date base image for Alpine."
      - "org.label-schema.url=https://github.com/Didstopia/docker-base-images"
      - "org.label-schema.vcs-url=github.com:Didstopia/docker-base-images.git"
      - "org.label-schema.vcs-ref={fcommitid}"
      - "org.label-schema.schema-version=1.0"
  
  nodejs-alpine-3.5:
    context: /
    dockerfile: Dockerfiles/Alpine/3.5/nodejs/Dockerfile
    depends_on:
      - alpine-3.5
    pushes:
      - "on_branch:master=didstopia/base:nodejs-alpine-3.5"
    labels:
      - "org.label-schema.vendor=Didstopia"
      - "org.label-schema.name=Base Docker image for Node.js LTS."
      - "org.label-schema.version=nodejs-alpine-3.5"
      - "org.label-schema.description=An always up to date base image for Node.js LTS."
      - "org.label-schema.url=https://github.com/Didstopia/docker-base-images"
      - "org.label-schema.vcs-url=github.com:Didstopia/docker-base-images.git"
      - "org.label-schema.vcs-ref={fcommitid}"
      - "org.label-schema.schema-version=1.0"
