# Run as root
sudo: required

# No specific environment necessary
language: generic

# Install Docker support
services:
  - docker

# Prepare the environment
before_script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then .travis/setup.sh; fi'

# Build, test and push the new images, with PR specific logic
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then source .travis/update_check.sh; fi'
  - .travis/build.sh
  - .travis/test.sh
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then .travis/push.sh; fi'

# Only build the master branch
branches:
  only:
  - master
