# Run as root
sudo: required

# No specific environment necessary
language: generic

# Install Docker support
services:
  - docker

# Prepare the environment
before_script:
  - .travis/setup.sh

## FIXME: The "source" part seems to be messing everything up,
##        not sure what we can do about it though
# Build, test and push the new images, with PR specific logic
script:
  - cd .travis && source update_check.sh
  - .travis/build.sh
  - .travis/test.sh
  - .travis/push.sh

# Only build the master branch
branches:
  only:
  - master
  - development
