# Run as root
sudo: required

# No specific environment necessary
language: generic

# Install Docker support
services:
  - docker

# Prepare the environment
before_script:
  - bash .travis/setup.sh

# Build, test and push the new images, with PR specific logic
script:
  - source .travis/update_check.sh
  - bash .travis/build.sh
  - bash .travis/test.sh
  - bash .travis/push.sh

# Only build the master branch
branches:
  only:
  - master
  - development
