# Run as root
sudo: required

# No specific environment necessary
language: generic

# Install Docker support
services:
  - docker

# Setup global environment variables
env:
  global:
    - DOCKER_CACHE_DIR=$HOME/.cache/docker
    - DOCKER_CACHE_BASE_FILE=$DOCKER_CACHE_DIR/base.tar.gz

# Setup caching
cache:
  directories:
    - $DOCKER_CACHE_DIR

# Load cached data and prepare the environment
before_install:
  - if [ -f ${DOCKER_CACHE_BASE_FILE} ]; then ls -sh ${DOCKER_CACHE_BASE_FILE}; gunzip -c ${DOCKER_CACHE_BASE_FILE} | docker load; fi
  - echo "Current directory: $(pwd)" && echo "Contents:" && ls && .travis/setup.sh
  - echo "Current directory: $(pwd)" && echo "Contents:" && ls && source .travis/update_check.sh

# Build the images
install:
  - echo "Current directory: $(pwd)" && echo "Contents:" && ls && .travis/build.sh

# Cache images
after_install:
  - if [ ! -d ${DOCKER_CACHE_DIR} ]; then mkdir -p ${DOCKER_CACHE_DIR}; fi
  - if [ ! -f ${DOCKER_CACHE_BASE_FILE} ]; then docker save didstopia/base | gzip > ${DOCKER_CACHE_BASE_FILE}; ls -sh ${DOCKER_CACHE_BASE_FILE}; fi

# Test and push the images if necessary
script:
  - echo "Current directory: $(pwd)" && echo "Contents:" && ls && .travis/test.sh
  - echo "Current directory: $(pwd)" && echo "Contents:" && ls && .travis/push.sh

# Only build specific branches
branches:
  only:
    - master
    - development
